mappings:
  PerfectCMSImage_Validator: Sunnysideup\PerfectCMSImages\Filesystem\PerfectCMSImage_Validator
  PerfectCMSImagesBuildTaskCheckImages: Sunnysideup\PerfectCMSImages\Tasks\PerfectCMSImagesBuildTaskCheckImages
  PerfectCMSImageDataExtension: Sunnysideup\PerfectCMSImages\Model\File\PerfectCMSImageDataExtension
  PerfectCMSImagesUploadField: Sunnysideup\PerfectCMSImages\Forms\PerfectCMSImagesUploadField
