---
Name: perfect_cms_images
After:
  - 'framework/*'
  - 'cms/*'
Before: 
  - 'mysite/*'
---
Image:
  extensions:
    - PerfectCMSImageDataExtension

#we set this so low because all the images are double size...

GDBackend:
  default_quality: 70

